### ISSUE TITLE
敏感词汇哪里找的?

### ISSUE THREAD

**Issue by zhoufox** [observerss/textfilter#3]
200多k的敏感词哪找的?
去哪更新啊?

**Comment by observerss** [comment]
某垂直门户网站自己的，更新么管理员自己设定就好了

-- 
Jingchao Hu
Sent with Airmail

On August 1, 2016 at 5:10:40 PM, zhou (notifications@github.com) wrote:

200多k的敏感词哪找的?
去哪更新啊?
