### ISSUE TITLE
找不到Module

### ISSUE THREAD

**Issue by yanrs17** [observerss/textfilter#5]
运行以下代码的时候，
`from filter import DFAFilter`
显示：
Traceback (most recent call last):
  File "<string>", line 1, in 0
ImportError: No module named filter

如果在terminal运行
`pip install filter`
又说
Could not find a version that satisfies the requirement filter (from versions: )
No matching distribution found for filter

求告诉运行方法，谢谢！

**Comment by xtdx** [comment]
安装pip install textfilter
from textfilter.textfilter import DFAFilter
